baseURL = 'https://smraisul03.github.io/'
languageCode = 'en-us'
title = 'smraisul03@web'
theme = 'hugo-theme-shell'

[Params]

  description = " "
  [Params.Terminal]
  schema = "powershell"

  userName = "smraisul03"
  pcName = "web"
  workDir = "mydir"
  profile = "profile.txt"

  terminalDelay = 15

  activityDelay = 5

  description = """
  Hi. I'm Raisul. 
  Nice to meet you!

  """


  [Params.Tree]
  use = true
  folderName = "my_activity"
  files = [ 
    ["About", "/post/about.md"],
    ["Projects", "/post/projects.md"],
    ["Github", "https://www.github.com/smraisul03"],
    ["LinkedIn", "https://www.linkedin.com/in/smraisul03"], 
  ]

